version: '3'

services:
  web:
    container_name: copy_university
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:silvera.mytestingenlocal.ml"
      - "traefik.port=3000"
    networks:
      - web

networks:
  web: